export const initialTracks = [
  {
    "id": "global-1",
    "rank": 1,
    "title": "Die With A Smile",
    "artist": "Lady Gaga & Bruno Mars",
    "region": "GLOBAL",
    "source": "Spotify Global / Billboard Hot 100",
    "genre": "Pop / Soul",
    "likes_count": 142,
    "preview_url": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/4a/12/34/4a1234c0-038c-f0cf-7953-aeebf84391e9/mzaf_782071858178876495.plus.aac.p.m4a",
    "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Lady%20Gaga%20%26%20Bruno%20Mars%20Die%20With%20A%20Smile"
  },
  {
    "id": "global-2",
    "rank": 2,
    "title": "BIRDS OF A FEATHER",
    "artist": "Billie Eilish",
    "region": "GLOBAL",
    "source": "Spotify Global Top 50",
    "genre": "Alt-Pop",
    "likes_count": 128,
    "preview_url": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview122/v4/2b/b9/7d/2bb97df9-cfbe-6385-df3a-3375cb450a18/mzaf_16238647754659359051.plus.aac.p.m4a",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Billie%20Eilish%20BIRDS%20OF%20A%20FEATHER"
  },
  {
    "id": "global-3",
    "rank": 3,
    "title": "Espresso",
    "artist": "Sabrina Carpenter",
    "region": "GLOBAL",
    "source": "Billboard Hot 100 / Spotify Global",
    "genre": "Nu-Disco / Pop",
    "likes_count": 119,
    "preview_url": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/cd/69/89/cd698944-e2b2-5fce-4cba-7a3d3ba5ec45/mzaf_1578335804368149870.plus.aac.p.m4a",
    "image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Sabrina%20Carpenter%20Espresso"
  },
  {
    "id": "global-4",
    "rank": 4,
    "title": "Taste",
    "artist": "Sabrina Carpenter",
    "region": "GLOBAL",
    "source": "Spotify Global / Apple Music",
    "genre": "Pop Rock",
    "likes_count": 98,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Sabrina%20Carpenter%20Taste"
  },
  {
    "id": "global-5",
    "rank": 5,
    "title": "APT.",
    "artist": "ROSÉ & Bruno Mars",
    "region": "GLOBAL",
    "source": "Billboard Global 200 / Spotify Top 50",
    "genre": "Pop Punk / Pop",
    "likes_count": 114,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/ROS%C3%89%20%26%20Bruno%20Mars%20APT."
  },
  {
    "id": "global-6",
    "rank": 6,
    "title": "Good Luck, Babe!",
    "artist": "Chappell Roan",
    "region": "GLOBAL",
    "source": "Spotify Global / Apple Music",
    "genre": "Synth-Pop",
    "likes_count": 85,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Chappell%20Roan%20Good%20Luck%2C%20Babe!"
  },
  {
    "id": "global-7",
    "rank": 7,
    "title": "Not Like Us",
    "artist": "Kendrick Lamar",
    "region": "GLOBAL",
    "source": "Billboard Hot 100 / Apple Music",
    "genre": "Hip-Hop / West Coast",
    "likes_count": 132,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://music.apple.com/search?term=Kendrick%20Lamar%20Not%20Like%20Us"
  },
  {
    "id": "global-8",
    "rank": 8,
    "title": "A Bar Song (Tipsy)",
    "artist": "Shaboozey",
    "region": "GLOBAL",
    "source": "Billboard Hot 100",
    "genre": "Country Hip-Hop",
    "likes_count": 77,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Shaboozey%20A%20Bar%20Song%20(Tipsy)"
  },
  {
    "id": "global-9",
    "rank": 9,
    "title": "Beautiful Things",
    "artist": "Benson Boone",
    "region": "GLOBAL",
    "source": "Spotify Global / Billboard",
    "genre": "Pop Rock",
    "likes_count": 64,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Benson%20Boone%20Beautiful%20Things"
  },
  {
    "id": "global-10",
    "rank": 10,
    "title": "Lose Control",
    "artist": "Teddy Swims",
    "region": "GLOBAL",
    "source": "Billboard Hot 100",
    "genre": "Soul / R&B",
    "likes_count": 91,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1447069387593-a5de076249c5?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Teddy%20Swims%20Lose%20Control"
  },
  {
    "id": "global-11",
    "rank": 11,
    "title": "Timeless",
    "artist": "The Weeknd & Playboi Carti",
    "region": "GLOBAL",
    "source": "Apple Music Global / Spotify",
    "genre": "Dark R&B / Trap",
    "likes_count": 103,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://music.apple.com/search?term=The%20Weeknd%20%26%20Playboi%20Carti%20Timeless"
  },
  {
    "id": "global-12",
    "rank": 12,
    "title": "Too Sweet",
    "artist": "Hozier",
    "region": "GLOBAL",
    "source": "Spotify Global Top 50",
    "genre": "Indie Rock / Blues",
    "likes_count": 72,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Hozier%20Too%20Sweet"
  },
  {
    "id": "global-13",
    "rank": 13,
    "title": "I Had Some Help",
    "artist": "Post Malone feat. Morgan Wallen",
    "region": "GLOBAL",
    "source": "Billboard Hot 100",
    "genre": "Country Pop",
    "likes_count": 58,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Post%20Malone%20feat.%20Morgan%20Wallen%20I%20Had%20Some%20Help"
  },
  {
    "id": "global-14",
    "rank": 14,
    "title": "Please Please Please",
    "artist": "Sabrina Carpenter",
    "region": "GLOBAL",
    "source": "Spotify Global",
    "genre": "Disco Pop",
    "likes_count": 67,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Sabrina%20Carpenter%20Please%20Please%20Please"
  },
  {
    "id": "global-15",
    "rank": 15,
    "title": "Disease",
    "artist": "Lady Gaga",
    "region": "GLOBAL",
    "source": "Apple Music Global",
    "genre": "Dark Electropop",
    "likes_count": 89,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://music.apple.com/search?term=Lady%20Gaga%20Disease"
  },
  {
    "id": "global-16",
    "rank": 16,
    "title": "MILLION DOLLAR BABY",
    "artist": "Tommy Richman",
    "region": "GLOBAL",
    "source": "Spotify Global / TikTok Viral",
    "genre": "Funk / R&B",
    "likes_count": 53,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Tommy%20Richman%20MILLION%20DOLLAR%20BABY"
  },
  {
    "id": "global-17",
    "rank": 17,
    "title": "Stargazing",
    "artist": "Myles Smith",
    "region": "GLOBAL",
    "source": "Spotify Global",
    "genre": "Folk Pop",
    "likes_count": 42,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Myles%20Smith%20Stargazing"
  },
  {
    "id": "global-18",
    "rank": 18,
    "title": "Guess",
    "artist": "Charli xcx feat. Billie Eilish",
    "region": "GLOBAL",
    "source": "Apple Music Global",
    "genre": "Hyperpop / Club",
    "likes_count": 76,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://music.apple.com/search?term=Charli%20xcx%20feat.%20Billie%20Eilish%20Guess"
  },
  {
    "id": "global-19",
    "rank": 19,
    "title": "we can't be friends",
    "artist": "Ariana Grande",
    "region": "GLOBAL",
    "source": "Billboard Hot 100",
    "genre": "Synth-Pop",
    "likes_count": 61,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Ariana%20Grande%20we%20can't%20be%20friends"
  },
  {
    "id": "global-20",
    "rank": 20,
    "title": "Si Antes Te Hubiera Conocido",
    "artist": "Karol G",
    "region": "GLOBAL",
    "source": "Spotify Global Top 50",
    "genre": "Merengue / Latin",
    "likes_count": 55,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Karol%20G%20Si%20Antes%20Te%20Hubiera%20Conocido"
  },
  {
    "id": "global-21",
    "rank": 21,
    "title": "feelslikeimfallinginlove",
    "artist": "Coldplay",
    "region": "GLOBAL",
    "source": "Spotify Global",
    "genre": "Alternative Pop",
    "likes_count": 48,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Coldplay%20feelslikeimfallinginlove"
  },
  {
    "id": "global-22",
    "rank": 22,
    "title": "Houdini",
    "artist": "Dua Lipa",
    "region": "GLOBAL",
    "source": "Billboard Global",
    "genre": "Dance-Pop / Nu-Disco",
    "likes_count": 52,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Dua%20Lipa%20Houdini"
  },
  {
    "id": "global-23",
    "rank": 23,
    "title": "I Love You, I'm Sorry",
    "artist": "Gracie Abrams",
    "region": "GLOBAL",
    "source": "Spotify Global Top 50",
    "genre": "Indie Pop",
    "likes_count": 39,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1447069387593-a5de076249c5?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Gracie%20Abrams%20I%20Love%20You%2C%20I'm%20Sorry"
  },
  {
    "id": "global-24",
    "rank": 24,
    "title": "Dancing In The Flames",
    "artist": "The Weeknd",
    "region": "GLOBAL",
    "source": "Apple Music Global",
    "genre": "Synth-Wave / Pop",
    "likes_count": 73,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://music.apple.com/search?term=The%20Weeknd%20Dancing%20In%20The%20Flames"
  },
  {
    "id": "global-25",
    "rank": 25,
    "title": "Fortnight",
    "artist": "Taylor Swift feat. Post Malone",
    "region": "GLOBAL",
    "source": "Billboard Hot 100 / Spotify",
    "genre": "Synth-Pop / Indie",
    "likes_count": 82,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Taylor%20Swift%20feat.%20Post%20Malone%20Fortnight"
  },
  {
    "id": "tr-1",
    "rank": 1,
    "title": "Geçiyor Zaman",
    "artist": "Semicenk",
    "region": "TR",
    "source": "Spotify Türkiye Top 50 / YouTube TR",
    "genre": "Türkçe Pop / Slow",
    "likes_count": 165,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Semicenk%20Ge%C3%A7iyor%20Zaman"
  },
  {
    "id": "tr-2",
    "rank": 2,
    "title": "DOĞUŞTAN BERİ BERABERİZ",
    "artist": "Lvbel C5",
    "region": "TR",
    "source": "Spotify TR / YouTube Music TR",
    "genre": "Türkçe Trap / Hip-Hop",
    "likes_count": 149,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Lvbel%20C5%20DO%C4%9EU%C5%9ETAN%20BER%C4%B0%20BERABER%C4%B0Z"
  },
  {
    "id": "tr-3",
    "rank": 3,
    "title": "GÜZEL VE İDDİALI",
    "artist": "BLOK3",
    "region": "TR",
    "source": "Spotify Türkiye Top 50",
    "genre": "Türkçe Drill / Trap",
    "likes_count": 138,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/BLOK3%20G%C3%9CZEL%20VE%20%C4%B0DD%C4%B0ALI"
  },
  {
    "id": "tr-4",
    "rank": 4,
    "title": "GELMEZSEN GELME",
    "artist": "Motive",
    "region": "TR",
    "source": "Apple Music Türkiye / Spotify TR",
    "genre": "Türkçe Rap / Hip-Hop",
    "likes_count": 112,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://music.apple.com/search?term=Motive%20GELMEZSEN%20GELME"
  },
  {
    "id": "tr-5",
    "rank": 5,
    "title": "Lan",
    "artist": "Zeynep Bastık",
    "region": "TR",
    "source": "YouTube Music TR / Spotify TR",
    "genre": "Türkçe Pop",
    "likes_count": 125,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://music.youtube.com/search?q=Zeynep%20Bast%C4%B1k%20Lan"
  },
  {
    "id": "tr-6",
    "rank": 6,
    "title": "CANEY",
    "artist": "UZI",
    "region": "TR",
    "source": "Spotify Türkiye Top 50",
    "genre": "Türkçe Street Rap",
    "likes_count": 104,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/UZI%20CANEY"
  },
  {
    "id": "tr-7",
    "rank": 7,
    "title": "En Dibine Kadar",
    "artist": "Dedublüman & Mavzer Tabancas",
    "region": "TR",
    "source": "Spotify TR / YouTube Music",
    "genre": "Alternatif Rock",
    "likes_count": 95,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Dedubl%C3%BCman%20%26%20Mavzer%20Tabancas%20En%20Dibine%20Kadar"
  },
  {
    "id": "tr-8",
    "rank": 8,
    "title": "Renklensin",
    "artist": "Reynmen",
    "region": "TR",
    "source": "YouTube Music TR / Spotify TR",
    "genre": "Türkçe Pop / R&B",
    "likes_count": 88,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://music.youtube.com/search?q=Reynmen%20Renklensin"
  },
  {
    "id": "tr-9",
    "rank": 9,
    "title": "Ateşe Düştüm",
    "artist": "Mert Demir",
    "region": "TR",
    "source": "Spotify Türkiye / Apple Music",
    "genre": "R&B / Alternatif Pop",
    "likes_count": 110,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Mert%20Demir%20Ate%C5%9Fe%20D%C3%BC%C5%9Ft%C3%BCm"
  },
  {
    "id": "tr-10",
    "rank": 10,
    "title": "Önümüz Yaz",
    "artist": "Simge",
    "region": "TR",
    "source": "Spotify TR / Apple Music TR",
    "genre": "Türkçe Pop / Dance",
    "likes_count": 79,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Simge%20%C3%96n%C3%BCm%C3%BCz%20Yaz"
  },
  {
    "id": "tr-11",
    "rank": 11,
    "title": "Ortak",
    "artist": "Melike Şahin",
    "region": "TR",
    "source": "Spotify TR Top 50",
    "genre": "Neo-Alaturka / Pop",
    "likes_count": 83,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Melike%20%C5%9Eahin%20Ortak"
  },
  {
    "id": "tr-12",
    "rank": 12,
    "title": "Ali Cabbar",
    "artist": "Emir Can İğrek",
    "region": "TR",
    "source": "Spotify TR / YouTube TR",
    "genre": "Akustik Pop / Hikaye",
    "likes_count": 92,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1447069387593-a5de076249c5?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Emir%20Can%20%C4%B0%C4%9Frek%20Ali%20Cabbar"
  },
  {
    "id": "tr-13",
    "rank": 13,
    "title": "Aklına Ben Gelicem",
    "artist": "BLOK3",
    "region": "TR",
    "source": "Spotify Türkiye Top 50",
    "genre": "Türkçe Drill / Trap",
    "likes_count": 87,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/BLOK3%20Akl%C4%B1na%20Ben%20Gelicem"
  },
  {
    "id": "tr-14",
    "rank": 14,
    "title": "Pişman Değilim",
    "artist": "Semicenk & Doğu Swag",
    "region": "TR",
    "source": "Spotify TR / YouTube Music",
    "genre": "Pop / Arabesk Trap",
    "likes_count": 74,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Semicenk%20%26%20Do%C4%9Fu%20Swag%20Pi%C5%9Fman%20De%C4%9Filim"
  },
  {
    "id": "tr-15",
    "rank": 15,
    "title": "SUBMARINER",
    "artist": "Lvbel C5",
    "region": "TR",
    "source": "Spotify TR / YouTube TR",
    "genre": "Türkçe Trap",
    "likes_count": 69,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Lvbel%20C5%20SUBMARINER"
  },
  {
    "id": "tr-16",
    "rank": 16,
    "title": "Antidepresan",
    "artist": "Mabel Matiz & Mert Demir",
    "region": "TR",
    "source": "Spotify TR / Apple Music TR",
    "genre": "Alternatif Pop / Elektronik",
    "likes_count": 99,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Mabel%20Matiz%20%26%20Mert%20Demir%20Antidepresan"
  },
  {
    "id": "tr-17",
    "rank": 17,
    "title": "Benden Bir Tane Daha Yok",
    "artist": "Hande Yener",
    "region": "TR",
    "source": "Apple Music Türkiye",
    "genre": "Elektronik / Dance-Pop",
    "likes_count": 62,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://music.apple.com/search?term=Hande%20Yener%20Benden%20Bir%20Tane%20Daha%20Yok"
  },
  {
    "id": "tr-18",
    "rank": 18,
    "title": "Mayhoş",
    "artist": "Edis",
    "region": "TR",
    "source": "Spotify TR / YouTube TR",
    "genre": "Türkçe Dans-Pop",
    "likes_count": 54,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Edis%20Mayho%C5%9F"
  },
  {
    "id": "tr-19",
    "rank": 19,
    "title": "Bir Tek Ben Anlarım",
    "artist": "KÖFN",
    "region": "TR",
    "source": "Spotify Türkiye Top 50",
    "genre": "Elektronik Pop",
    "likes_count": 78,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/K%C3%96FN%20Bir%20Tek%20Ben%20Anlar%C4%B1m"
  },
  {
    "id": "tr-20",
    "rank": 20,
    "title": "Seni Dert Etmeler",
    "artist": "Madrigal",
    "region": "TR",
    "source": "Spotify TR / Apple Music",
    "genre": "Indie Rock",
    "likes_count": 81,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Madrigal%20Seni%20Dert%20Etmeler"
  },
  {
    "id": "tr-21",
    "rank": 21,
    "title": "İmdat",
    "artist": "Çakal & Reckol",
    "region": "TR",
    "source": "Spotify TR / YouTube Music",
    "genre": "Türkçe Trap",
    "likes_count": 57,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/%C3%87akal%20%26%20Reckol%20%C4%B0mdat"
  },
  {
    "id": "tr-22",
    "rank": 22,
    "title": "İstanbul Beyefendisi",
    "artist": "Yaşlı Amca",
    "region": "TR",
    "source": "Spotify TR Top 50",
    "genre": "Alternatif Rock",
    "likes_count": 46,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1447069387593-a5de076249c5?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Ya%C5%9Fl%C4%B1%20Amca%20%C4%B0stanbul%20Beyefendisi"
  },
  {
    "id": "tr-23",
    "rank": 23,
    "title": "Milyoner",
    "artist": "UZI & Heijan",
    "region": "TR",
    "source": "YouTube Music TR",
    "genre": "Hip-Hop / Drill",
    "likes_count": 51,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://music.youtube.com/search?q=UZI%20%26%20Heijan%20Milyoner"
  },
  {
    "id": "tr-24",
    "rank": 24,
    "title": "Dünyanın En Güzel Kızı",
    "artist": "Mavi Gri",
    "region": "TR",
    "source": "Spotify TR Top 50",
    "genre": "Alternatif Pop Rock",
    "likes_count": 43,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Mavi%20Gri%20D%C3%BCnyan%C4%B1n%20En%20G%C3%BCzel%20K%C4%B1z%C4%B1"
  },
  {
    "id": "tr-25",
    "rank": 25,
    "title": "Beni Boş Yere Yorma",
    "artist": "Gripin & Gazapizm",
    "region": "TR",
    "source": "Spotify TR / YouTube TR",
    "genre": "Rock / Rap Düet",
    "likes_count": 66,
    "preview_url": "",
    "image_url": "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&auto=format&fit=crop&q=80",
    "player_url": "https://open.spotify.com/search/Gripin%20%26%20Gazapizm%20Beni%20Bo%C5%9F%20Yere%20Yorma"
  }
];
