export const initialTracks = [
  // GLOBAL TRENDS (Dünya)
  {
    id: 'global-1',
    rank: 1,
    title: 'Die With A Smile',
    artist: 'Lady Gaga & Bruno Mars',
    region: 'GLOBAL',
    source: 'Spotify Global / Billboard Hot 100',
    genre: 'Pop / Soul',
    likes_count: 142,
    preview_url: 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/4a/12/34/4a1234c0-038c-f0cf-7953-aeebf84391e9/mzaf_782071858178876495.plus.aac.p.m4a',
    image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-2',
    rank: 2,
    title: 'BIRDS OF A FEATHER',
    artist: 'Billie Eilish',
    region: 'GLOBAL',
    source: 'Spotify Global Top 50',
    genre: 'Alt-Pop',
    likes_count: 128,
    preview_url: 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview122/v4/2b/b9/7d/2bb97df9-cfbe-6385-df3a-3375cb450a18/mzaf_16238647754659359051.plus.aac.p.m4a',
    image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-3',
    rank: 3,
    title: 'Espresso',
    artist: 'Sabrina Carpenter',
    region: 'GLOBAL',
    source: 'Billboard Hot 100 / Spotify Global',
    genre: 'Nu-Disco / Pop',
    likes_count: 119,
    preview_url: 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/cd/69/89/cd698944-e2b2-5fce-4cba-7a3d3ba5ec45/mzaf_1578335804368149870.plus.aac.p.m4a',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-4',
    rank: 4,
    title: 'Taste',
    artist: 'Sabrina Carpenter',
    region: 'GLOBAL',
    source: 'Spotify Global / Apple Music',
    genre: 'Pop Rock',
    likes_count: 98,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-5',
    rank: 5,
    title: 'APT.',
    artist: 'ROSÉ & Bruno Mars',
    region: 'GLOBAL',
    source: 'Billboard Global 200 / Spotify Top 50',
    genre: 'Pop Punk / Pop',
    likes_count: 114,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-6',
    rank: 6,
    title: 'Good Luck, Babe!',
    artist: 'Chappell Roan',
    region: 'GLOBAL',
    source: 'Spotify Global / Apple Music',
    genre: 'Synth-Pop',
    likes_count: 85,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-7',
    rank: 7,
    title: 'Not Like Us',
    artist: 'Kendrick Lamar',
    region: 'GLOBAL',
    source: 'Billboard Hot 100 / Apple Music',
    genre: 'Hip-Hop / West Coast',
    likes_count: 132,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-8',
    rank: 8,
    title: 'A Bar Song (Tipsy)',
    artist: 'Shaboozey',
    region: 'GLOBAL',
    source: 'Billboard Hot 100',
    genre: 'Country Hip-Hop',
    likes_count: 77,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-9',
    rank: 9,
    title: 'Beautiful Things',
    artist: 'Benson Boone',
    region: 'GLOBAL',
    source: 'Spotify Global / Billboard',
    genre: 'Pop Rock',
    likes_count: 64,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-10',
    rank: 10,
    title: 'Lose Control',
    artist: 'Teddy Swims',
    region: 'GLOBAL',
    source: 'Billboard Hot 100',
    genre: 'Soul / R&B',
    likes_count: 91,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1447069387593-a5de076249c5?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-11',
    rank: 11,
    title: 'Timeless',
    artist: 'The Weeknd & Playboi Carti',
    region: 'GLOBAL',
    source: 'Apple Music Global / Spotify',
    genre: 'Dark R&B / Trap',
    likes_count: 103,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-12',
    rank: 12,
    title: 'Too Sweet',
    artist: 'Hozier',
    region: 'GLOBAL',
    source: 'Spotify Global Top 50',
    genre: 'Indie Rock / Blues',
    likes_count: 72,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-13',
    rank: 13,
    title: 'I Had Some Help',
    artist: 'Post Malone feat. Morgan Wallen',
    region: 'GLOBAL',
    source: 'Billboard Hot 100',
    genre: 'Country Pop',
    likes_count: 58,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-14',
    rank: 14,
    title: 'Please Please Please',
    artist: 'Sabrina Carpenter',
    region: 'GLOBAL',
    source: 'Spotify Global',
    genre: 'Disco Pop',
    likes_count: 67,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-15',
    rank: 15,
    title: 'Disease',
    artist: 'Lady Gaga',
    region: 'GLOBAL',
    source: 'Apple Music Global',
    genre: 'Dark Electropop',
    likes_count: 89,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-16',
    rank: 16,
    title: 'MILLION DOLLAR BABY',
    artist: 'Tommy Richman',
    region: 'GLOBAL',
    source: 'Spotify Global / TikTok Viral',
    genre: 'Funk / R&B',
    likes_count: 53,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-17',
    rank: 17,
    title: 'Stargazing',
    artist: 'Myles Smith',
    region: 'GLOBAL',
    source: 'Spotify Global',
    genre: 'Folk Pop',
    likes_count: 42,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-18',
    rank: 18,
    title: 'Guess',
    artist: 'Charli xcx feat. Billie Eilish',
    region: 'GLOBAL',
    source: 'Apple Music Global',
    genre: 'Hyperpop / Club',
    likes_count: 76,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-19',
    rank: 19,
    title: 'we can\'t be friends',
    artist: 'Ariana Grande',
    region: 'GLOBAL',
    source: 'Billboard Hot 100',
    genre: 'Synth-Pop',
    likes_count: 61,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-20',
    rank: 20,
    title: 'Si Antes Te Hubiera Conocido',
    artist: 'Karol G',
    region: 'GLOBAL',
    source: 'Spotify Global Top 50',
    genre: 'Merengue / Latin',
    likes_count: 55,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-21',
    rank: 21,
    title: 'feelslikeimfallinginlove',
    artist: 'Coldplay',
    region: 'GLOBAL',
    source: 'Spotify Global',
    genre: 'Alternative Pop',
    likes_count: 48,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-22',
    rank: 22,
    title: 'Houdini',
    artist: 'Dua Lipa',
    region: 'GLOBAL',
    source: 'Billboard Global',
    genre: 'Dance-Pop / Nu-Disco',
    likes_count: 52,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-23',
    rank: 23,
    title: 'I Love You, I\'m Sorry',
    artist: 'Gracie Abrams',
    region: 'GLOBAL',
    source: 'Spotify Global Top 50',
    genre: 'Indie Pop',
    likes_count: 39,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1447069387593-a5de076249c5?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-24',
    rank: 24,
    title: 'Dancing In The Flames',
    artist: 'The Weeknd',
    region: 'GLOBAL',
    source: 'Apple Music Global',
    genre: 'Synth-Wave / Pop',
    likes_count: 73,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'global-25',
    rank: 25,
    title: 'Fortnight',
    artist: 'Taylor Swift feat. Post Malone',
    region: 'GLOBAL',
    source: 'Billboard Hot 100 / Spotify',
    genre: 'Synth-Pop / Indie',
    likes_count: 82,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=300&auto=format&fit=crop&q=80'
  },

  // TÜRKİYE TRENDLERİ
  {
    id: 'tr-1',
    rank: 1,
    title: 'Geçiyor Zaman',
    artist: 'Semicenk',
    region: 'TR',
    source: 'Spotify Türkiye Top 50 / YouTube TR',
    genre: 'Türkçe Pop / Slow',
    likes_count: 165,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-2',
    rank: 2,
    title: 'DOĞUŞTAN BERİ BERABERİZ',
    artist: 'Lvbel C5',
    region: 'TR',
    source: 'Spotify TR / YouTube Music TR',
    genre: 'Türkçe Trap / Hip-Hop',
    likes_count: 149,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-3',
    rank: 3,
    title: 'GÜZEL VE İDDİALI',
    artist: 'BLOK3',
    region: 'TR',
    source: 'Spotify Türkiye Top 50',
    genre: 'Türkçe Drill / Trap',
    likes_count: 138,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-4',
    rank: 4,
    title: 'GELMEZSEN GELME',
    artist: 'Motive',
    region: 'TR',
    source: 'Apple Music Türkiye / Spotify TR',
    genre: 'Türkçe Rap / Hip-Hop',
    likes_count: 112,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-5',
    rank: 5,
    title: 'Lan',
    artist: 'Zeynep Bastık',
    region: 'TR',
    source: 'YouTube Music TR / Spotify TR',
    genre: 'Türkçe Pop',
    likes_count: 125,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-6',
    rank: 6,
    title: 'CANEY',
    artist: 'UZI',
    region: 'TR',
    source: 'Spotify Türkiye Top 50',
    genre: 'Türkçe Street Rap',
    likes_count: 104,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-7',
    rank: 7,
    title: 'En Dibine Kadar',
    artist: 'Dedublüman & Mavzer Tabancas',
    region: 'TR',
    source: 'Spotify TR / YouTube Music',
    genre: 'Alternatif Rock',
    likes_count: 95,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-8',
    rank: 8,
    title: 'Renklensin',
    artist: 'Reynmen',
    region: 'TR',
    source: 'YouTube Music TR / Spotify TR',
    genre: 'Türkçe Pop / R&B',
    likes_count: 88,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-9',
    rank: 9,
    title: 'Ateşe Düştüm',
    artist: 'Mert Demir',
    region: 'TR',
    source: 'Spotify Türkiye / Apple Music',
    genre: 'R&B / Alternatif Pop',
    likes_count: 110,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-10',
    rank: 10,
    title: 'Önümüz Yaz',
    artist: 'Simge',
    region: 'TR',
    source: 'Spotify TR / Apple Music TR',
    genre: 'Türkçe Pop / Dance',
    likes_count: 79,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-11',
    rank: 11,
    title: 'Ortak',
    artist: 'Melike Şahin',
    region: 'TR',
    source: 'Spotify TR Top 50',
    genre: 'Neo-Alaturka / Pop',
    likes_count: 83,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-12',
    rank: 12,
    title: 'Ali Cabbar',
    artist: 'Emir Can İğrek',
    region: 'TR',
    source: 'Spotify TR / YouTube TR',
    genre: 'Akustik Pop / Hikaye',
    likes_count: 92,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1447069387593-a5de076249c5?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-13',
    rank: 13,
    title: 'Aklına Ben Gelicem',
    artist: 'BLOK3',
    region: 'TR',
    source: 'Spotify Türkiye Top 50',
    genre: 'Türkçe Drill / Trap',
    likes_count: 87,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-14',
    rank: 14,
    title: 'Pişman Değilim',
    artist: 'Semicenk & Doğu Swag',
    region: 'TR',
    source: 'Spotify TR / YouTube Music',
    genre: 'Pop / Arabesk Trap',
    likes_count: 74,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-15',
    rank: 15,
    title: 'SUBMARINER',
    artist: 'Lvbel C5',
    region: 'TR',
    source: 'Spotify TR / YouTube TR',
    genre: 'Türkçe Trap',
    likes_count: 69,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-16',
    rank: 16,
    title: 'Antidepresan',
    artist: 'Mabel Matiz & Mert Demir',
    region: 'TR',
    source: 'Spotify TR / Apple Music TR',
    genre: 'Alternatif Pop / Elektronik',
    likes_count: 99,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-17',
    rank: 17,
    title: 'Benden Bir Tane Daha Yok',
    artist: 'Hande Yener',
    region: 'TR',
    source: 'Apple Music Türkiye',
    genre: 'Elektronik / Dance-Pop',
    likes_count: 62,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-18',
    rank: 18,
    title: 'Mayhoş',
    artist: 'Edis',
    region: 'TR',
    source: 'Spotify TR / YouTube TR',
    genre: 'Türkçe Dans-Pop',
    likes_count: 54,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-19',
    rank: 19,
    title: 'Bir Tek Ben Anlarım',
    artist: 'KÖFN',
    region: 'TR',
    source: 'Spotify Türkiye Top 50',
    genre: 'Elektronik Pop',
    likes_count: 78,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-20',
    rank: 20,
    title: 'Seni Dert Etmeler',
    artist: 'Madrigal',
    region: 'TR',
    source: 'Spotify TR / Apple Music',
    genre: 'Indie Rock',
    likes_count: 81,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-21',
    rank: 21,
    title: 'İmdat',
    artist: 'Çakal & Reckol',
    region: 'TR',
    source: 'Spotify TR / YouTube Music',
    genre: 'Türkçe Trap',
    likes_count: 57,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-22',
    rank: 22,
    title: 'İstanbul Beyefendisi',
    artist: 'Yaşlı Amca',
    region: 'TR',
    source: 'Spotify TR Top 50',
    genre: 'Alternatif Rock',
    likes_count: 46,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1447069387593-a5de076249c5?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-23',
    rank: 23,
    title: 'Milyoner',
    artist: 'UZI & Heijan',
    region: 'TR',
    source: 'YouTube Music TR',
    genre: 'Hip-Hop / Drill',
    likes_count: 51,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-24',
    rank: 24,
    title: 'Dünyanın En Güzel Kızı',
    artist: 'Mavi Gri',
    region: 'TR',
    source: 'Spotify TR Top 50',
    genre: 'Alternatif Pop Rock',
    likes_count: 43,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-25',
    rank: 25,
    title: 'Beni Boş Yere Yorma',
    artist: 'Gripin & Gazapizm',
    region: 'TR',
    source: 'Spotify TR / YouTube TR',
    genre: 'Rock / Rap Düet',
    likes_count: 66,
    preview_url: '',
    image_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&auto=format&fit=crop&q=80'
  }
];
